// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package example

import (
	"testing"
	"unicode/utf8"
)

func TestCopy(t *testing.T) {
	app, err := NewStreamingApplication("test-application-copy", "unit-test", "127.0.0.1:9092")
	if err != nil {
		t.Errorf("init app: %v", err)
	}

	app.
		StreamTopic("test-topic-in").
		MapValues(func(v KafkaValue) KafkaValue { return []byte(reverse(string(v))) }).
		WriteTo(app, "test-topic-out")

	err = app.Run()
	if err != nil {
		t.Errorf("run app: %v", err)
	}

	err = app.Close()
	if err != nil {
		t.Errorf("close app: %v", err)
	}
}

func reverse(s string) string {
	o := make([]rune, utf8.RuneCountInString(s))
	i := len(o)
	for _, c := range s {
		i--
		o[i] = c
	}
	return string(o)
}
