// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package example

import (
	"log"

	"google.golang.org/protobuf/proto"
)

func DecodeProduct(bb []byte) *Product {
	var p *Product
	err := proto.Unmarshal(bb, p)
	if err != nil {
		log.Fatalf("encode product: %v", err)
	}

	return p
}

func EncodeProduct(p *Product) []byte {
	out, err := proto.Marshal(p)
	if err != nil {
		log.Fatalf("encode product: %v", err)
	}

	return out
}
